/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./theme/components/Badge.vue')['default']
    'Bi:fileEarmarkWordFill': typeof import('~icons/bi/file-earmark-word-fill')['default']
    'Bi:github': typeof import('~icons/bi/github')['default']
    CloudinaryImg: typeof import('./theme/components/CloudinaryImg.vue')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    CopyRight: typeof import('./theme/components/CopyRight.vue')['default']
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    'EosIcons:modifiedDate': typeof import('~icons/eos-icons/modified-date')['default']
    'Fa6Solid:copyright': typeof import('~icons/fa6-solid/copyright')['default']
    'Fe:youtube': typeof import('~icons/fe/youtube')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    'IconPark:addWeb': typeof import('~icons/icon-park/add-web')['default']
    'Logos:reactQueryIcon': typeof import('~icons/logos/react-query-icon')['default']
    'Logos:vue': typeof import('~icons/logos/vue')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    'Octicon:feedPerson16': typeof import('~icons/octicon/feed-person16')['default']
    'Ooui:clock': typeof import('~icons/ooui/clock')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    'Ph:planetFill': typeof import('~icons/ph/planet-fill')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
    'Ri:mindMap': typeof import('~icons/ri/mind-map')['default']
    'SkillIcons:reactDark': typeof import('~icons/skill-icons/react-dark')['default']
    'SkillIcons:stackoverflowDark': typeof import('~icons/skill-icons/stackoverflow-dark')['default']
    'SkillIcons:typescript': typeof import('~icons/skill-icons/typescript')['default']
    'SkillIcons:vercelDark': typeof import('~icons/skill-icons/vercel-dark')['default']
    'Tabler:brandBilibili': typeof import('~icons/tabler/brand-bilibili')['default']
    'Tabler:brandJuejin': typeof import('~icons/tabler/brand-juejin')['default']
    'Tabler:curling': typeof import('~icons/tabler/curling')['default']
    'Teenyicons:nextjsSolid': typeof import('~icons/teenyicons/nextjs-solid')['default']
    'Uiw:weixin': typeof import('~icons/uiw/weixin')['default']
    VideoLink: typeof import('./theme/components/VideoLink.vue')['default']
    'VscodeIcons:fileTypeBun': typeof import('~icons/vscode-icons/file-type-bun')['default']
  }
}
