/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./theme/components/Badge.vue')['default']
    'Bi:fileEarmarkWordFill': typeof import('~icons/bi/file-earmark-word-fill')['default']
    CloudinaryImg: typeof import('./theme/components/CloudinaryImg.vue')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    CopyRight: typeof import('./theme/components/CopyRight.vue')['default']
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    'EosIcons:modifiedDate': typeof import('~icons/eos-icons/modified-date')['default']
    'Fa6Solid:copyright': typeof import('~icons/fa6-solid/copyright')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    'Octicon:feedPerson16': typeof import('~icons/octicon/feed-person16')['default']
    'Ooui:clock': typeof import('~icons/ooui/clock')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    'RadixIcons:update': typeof import('~icons/radix-icons/update')['default']
    VideoLink: typeof import('./theme/components/VideoLink.vue')['default']
  }
}
