name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "20.X"
      
      - name: install deps
        run: npm install
      
      - name: build app
        run: npm run docs:build
      
      - name: Check study-docs directory
        id: check_study-docs
        run: |
          if [ -n "$(ls -A study-docs/)" ]; then
            echo "study-docs_not_empty=true" >> $GITHUB_OUTPUT
          else
            echo "study-docs_not_empty=false" >> $GITHUB_OUTPUT
          fi
      
      - name: copy new files
        uses: appleboy/scp-action@master
        if: steps.check_study-docs.outputs.study-docs_not_empty == 'true'
        with:
          host: ${{ secrets.SERVER_IP }}
          username: administrator
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "study-docs/*"
          target: "C:/nginx/html/study-docs"  # 明确指定服务器上的子目录
          strip_components: 1
          rm: false  # 禁用自动删除目标目录
          overwrite: true  # 确保覆盖现有文件