name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "20.X"
      
      - name: install deps
        run: npm install
      
      - name: build app
        run: npm run docs:build
      
      - name: Check dist directory
        id: check_dist
        run: |
          if [ -n "$(ls -A dist/)" ]; then
            echo "dist_not_empty=true" >> $GITHUB_OUTPUT
          else
            echo "dist_not_empty=false" >> $GITHUB_OUTPUT
          fi
      
      - name: copy new files
        uses: appleboy/scp-action@master
        if: steps.check_dist.outputs.dist_not_empty == 'true'
        with:
          host: ${{ secrets.SERVER_IP }}
          username: administrator
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "dist/*"
          target: "C:/nginx/html"
          strip_components: 1
          rm: true  # 添加这个选项来删除目标目录中不存在于源中的文件